# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: /home/circleci/project
    steps:
      - checkout

      - run: sudo npm install -g npm@latest

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      # Test package install
      - run:
          name: Test package install
          command: |
            cd ../
            mkdir test
            cd test
            npm init -yes
            npm install chatwork/td-workflow-development-kit#$CIRCLE_BRANCH
