# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: /home/circleci/project
    steps:
      - checkout

      - run:
          name: NPM Update
          command: sudo npm install -g npm@latest

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Package install test
          command: |
            cd ../
            mkdir test
            cd test
            npm init -yes
            npm install chatwork/td-workflow-development-kit#$CIRCLE_BRANCH
            $(npm bin)/td-wdk set-api hogehoge
            $(npm bin)/td-wdk create
            $(npm bin)/td-wdk build
