env:
  prd:
    projectName: sample-project
    param:
      td:
        database: sample_db
        table: sample_table
        result_table: result_sample_table
  dev:
    projectName: sample-project-dev
    param:
      td:
        database: dev_db
        table: dev_table
        result_table: result_dev_table
  test:
    projectName: sample-project-test
    param:
      td:
        database: test_db
        table: test_table
        result_table: result_test_table
test:
  database: test_db
  envParam: test
  workflows:
    - filePath: sample.dig
  tables:
    - name: test_table
      dataFilePath: csv/test_table.csv
      schemaFilePath: schema/test_schema.yaml
    - name: expect_table
      dataFilePath: csv/expect_table.csv
      schemaFilePath: schema/expect_schema.yaml
  expects:
    - srcTable: result_test_table
      expectTable: expect_table
      columns:
        - name
        - total
