env:
  prd:
    projectName: sample-project
    param:
      td:
        database: sample-db
        table: sample-table
        result_table: result-sample-table
  dev:
    projectName: sample-project-dev
    param:
      td:
        database: dev-db
        table: dev-table
        result_table: result-dev-table
  test:
    projectName: sample-project-test
    param:
      td:
        database: test-db
        table: test-table
        result_table: result-test-table
test:
  database: test-db
  envParam: test
  workflows:
    - file: sample.dig
  tables:
    - name: test-table
      dataFile: csv/test-table.csv
      schemaFile: schema/schema.yaml
    - name: expect-table
      dataFile: csv/expect-table.csv
      schemaFile: schema/schema.yaml
  expects:
    - srcTable: result-test-table
      expectTable: expect-table
      columns:
        - id
        - account_id
        - name
